Вот черновая заметка по материалам нового видео, продолжающая серию в том же стиле и с сохранением оригинальной англоязычной терминологии:

### Заметка: Введение в NumPy (Introduction to NumPy)

**Основная концепция**
*   **NumPy** — это базовая библиотека для работы с массивами и вычислениями в Python, которая повсеместно используется в Data Science и Machine Learning.
*   Общепринятая конвенция (convention) при импорте — использовать сокращение **`np`**: `import numpy as np`.

**Создание одномерных массивов (Creating Arrays)**
NumPy предлагает несколько удобных функций для быстрой генерации массивов:
*   `np.zeros(size)` — создает массив (**array**), заполненный нулями.
*   `np.ones(size)` — создает массив, заполненный единицами.
*   `np.full(size, number)` — заполняет массив произвольным указанным числом (например, 2.5).
*   `np.array(list)` — конвертирует обычный список Python (**python list**) в массив NumPy.
*   `np.arange(start, end)` — генерирует диапазон чисел (по аналогии со стандартной функцией `range` в Python). Последнее число не включается в массив (**exclusive**).
*   `np.linspace(start, end, size)` — создает массив заданного размера, равномерно заполненный числами от начального до конечного значения (включительно).

**Многомерные массивы (Multi-dimensional arrays)**
*   В NumPy легко создавать двумерные (**two-dimensional**) и многомерные массивы. Для этого функциям вроде `zeros` нужно передать размерность в виде `(rows, columns)` — количество строк и столбцов.
*   Двумерный массив также можно создать, передав в `np.array()` список списков (**list of lists**).

**Индексация и доступ к элементам (Indexing)**
*   Как и в чистом Python, индексация в NumPy начинается с нуля.
*   Для доступа к элементам двумерного массива используются два индекса через запятую: `array[row_index, column_index]`.
*   **Slicing (срезы)**: чтобы получить всю строку, достаточно указать один индекс (например, `array`). Чтобы получить всю колонку, используется оператор двоеточия `[:]`, который означает «все строки» — например, `array[:, 1]` вернет колонку под индексом 1.
*   Любой выбранный элемент, строку или колонку можно перезаписать с помощью оператора присваивания (`=`).

**Генерация случайных чисел (Random generation)**
Пакет `np.random` позволяет генерировать массивы со случайными числами:
*   **Uniform distribution** (Равномерное распределение): генерация чисел от 0 до 1.
*   **Standard normal distribution** (Стандартное нормальное распределение): генерация чисел вокруг нуля.
*   **Random integers**: генерация целых чисел в заданном диапазоне (от `low` до `high`).
*   **Fixing the random seed**: Случайные числа в программировании на самом деле являются псевдослучайными (**pseudo-random**). Чтобы зафиксировать генератор и сделать результаты воспроизводимыми на разных компьютерах (**reproducible**), необходимо установить сид: `np.random.seed(number)`.

**Операции с массивами (Operations)**
1.  **Element-wise operations (Поэлементные операции)**
    *   В отличие от обычных списков Python, где потребовалось бы писать цикл `for`, в NumPy можно прибавлять, вычитать, умножать или делить числа прямо на весь массив (например, `array + 1` или `array * 100`).
    *   Операции можно объединять в цепочки (**chain**): `(array * 2) + 10`.
    *   Можно применять математические действия между двумя разными массивами одинакового размера — операция выполнится поэлементно.
2.  **Comparison operations (Операции сравнения)**
    *   Сравнения (например, `array >= 2` или `array1 > array2`) также выполняются поэлементно и возвращают массив булевых значений (`True` или `False`).
3.  **Boolean filtering (Фильтрация)**
    *   Если булево условие поместить в квадратные скобки к исходному массиву (например, `array[array >= 2]`), функция вернет только те элементы, для которых условие является истинным. 

**Агрегирующие операции (Summarizing operations)**
Вместо возвращения нового массива, эти операции вычисляют и возвращают одно число (статистику) по всему массиву:
*   `min()` — минимальное значение.
*   `max()` — максимальное значение.
*   `sum()` — сумма всех элементов.
*   `mean()` — среднее арифметическое.
*   `std()` — стандартное отклонение (**standard deviation**).
Эти операции работают как с одномерными, так и с многомерными массивами.

In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(7, 3)

array([3, 3, 3, 3, 3, 3, 3])

In [6]:
a = np.array([1,2,3,5])
a

array([1, 2, 3, 5])

In [8]:
a[2] = 5
a

array([1, 2, 5, 5])

In [11]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
n = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

In [17]:
first_element = n[0,0]
first_element

np.int64(1)

In [18]:
n[:, 1]

array([2, 5, 8])

In [ ]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [22]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [23]:
np.random.seed(2)
np.random.randint(low= 0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [25]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [28]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [29]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [30]:
a

array([0, 1, 2, 3, 4])

In [32]:
a >= 2

array([False, False,  True,  True,  True])

In [33]:
a > b

array([False, False,  True,  True,  True])

In [35]:
a[a > b]

array([2, 3, 4])

In [36]:
a

array([0, 1, 2, 3, 4])

In [37]:
a.min()

np.int64(0)

In [38]:
a.max()

np.int64(4)

In [39]:
a.sum()

np.int64(10)

In [41]:
a.mean()

np.float64(2.0)

In [42]:
a.std()

np.float64(1.4142135623730951)

In [43]:
n.sum()

np.int64(45)