Вот черновая заметка по материалам нового видео, продолжающая нашу серию. Как и просили, основная терминология сохранена на английском языке:

### Заметка: Основы линейной алгебры (Linear Algebra Refresher)

**Векторы и базовые операции**
*   В отличие от NumPy, где векторы часто представляются как строки, в традиционной линейной алгебре принято записывать векторы в виде столбцов (**column vector**).
*   **Умножение на число**: при умножении вектора на скалярное число (например, на 2), каждый элемент вектора просто умножается на это число.
*   **Сложение векторов (Vector addition)**: происходит поэлементно, точно так же, как мы это делали ранее в базовом NumPy.

**Умножение (Multiplication)**
В линейной алгебре нужно четко отличать обычное поэлементное умножение от алгебраического.

1.  **Vector-vector multiplication (Вектор на вектор)**
    *   Эта операция также называется скалярным произведением (**dot product**) или внутренним произведением (**inner product**).
    *   В отличие от поэлементного умножения, результатом *dot product* является **одно число**, а не новый массив.
    *   Оно вычисляется путем попарного умножения соответствующих элементов двух векторов с последующим суммированием результатов.
    *   Для правильной записи этой операции первый вектор должен быть строкой (**row vector**), а второй — столбцом. Для преобразования вектора-столбца в строку используется операция транспонирования (**transpose**).
    *   В NumPy эта операция легко выполняется с помощью встроенной функции `dot`.

2.  **Matrix-vector multiplication (Матрица на вектор)**
    *   При умножении матрицы `U` на вектор `v`, происходит вычисление **dot product** для каждой отдельной строки матрицы `U` с вектором `v`.
    *   Результатом такого умножения является новый вектор. Важное условие: количество колонок в матрице должно совпадать с количеством элементов в векторе.

3.  **Matrix-matrix multiplication (Матрица на матрицу)**
    *   Чтобы умножить матрицу `U` на матрицу `V`, мы разбиваем вторую матрицу `V` на отдельные колонки.
    *   После этого матрица `U` умножается на каждую из этих колонок (сводится к серии операций *matrix-vector multiplication*).
    *   В NumPy для перемножения двух матриц применяется тот же самый метод `dot`.

**Специальные матрицы и операции**

1.  **Identity matrix (Единичная матрица, `I`)**
    *   Это **квадратная матрица** (**square matrix**), у которой на главной диагонали расположены единицы, а все остальные значения — нули.
    *   В линейной алгебре она выполняет роль цифры "1": при умножении любой матрицы на матрицу `I` мы получаем исходную матрицу без изменений.
    *   В NumPy единичную матрицу можно создать с помощью функции `np.eye(size)`.

2.  **Matrix inverse (Обратная матрица, `A^-1`)**
    *   Обратная матрица — это такая матрица, при умножении исходной матрицы на которую мы получаем единичную матрицу `I`.
    *   Важное правило: обратную матрицу можно вычислить только для квадратных матриц (где количество строк равно количеству колонок).
    *   В NumPy для её нахождения используется функция `inv` из пакета для линейной алгебры: `np.linalg.inv()`.
    *   Вычисление обратной матрицы будет играть ключевую роль при реализации алгоритма линейной регрессии (**Linear Regression**) на следующих этапах.

In [1]:
import numpy as np

In [2]:
u = np.array([2,4,5,6])

In [3]:
v = np.array([1,0,0,2])

In [4]:
u + v

array([3, 4, 5, 8])

In [5]:
2 * u

array([ 4,  8, 10, 12])

In [7]:
# numpy multiplie vector vector it is not the same in linear algebra
u * v 

array([ 2,  0,  0, 12])

In [9]:
v.shape

(4,)

In [10]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0
    for i in range(n):
        result += u[i] * v[i]
    
    return result

In [11]:
vector_vector_multiplication(u, v)

np.int64(14)

In [12]:
# the same logic in vector method .dot()
u.dot(v)

np.int64(14)

In [13]:
U = np.array(
    [
        [2,4,5,6],
        [1,2,1,2],
        [3,1,2,1]
    ]
)

In [15]:
U.shape

(3, 4)

In [16]:
v.shape

(4,)

In [17]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    return result

In [18]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [ ]:
# the same logic as a custom function matrix_vector_multiplication()
U.dot(v)

array([14,  5,  5])

In [20]:
V = np.array(
    [
        [1, 1, 2],
        [0, 0.5, 1],
        [0, 2, 1],
        [2, 1, 0]
    ]
)

In [24]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [25]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [26]:
# The same logic like in matrix_matrix_multiplication
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [28]:
I = np.eye(3)

In [29]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [30]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [34]:
Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [35]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [36]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])